Date changed to Jan 12, 2021
Infinito-IIT-Patna/Infinito2020 pull request #19
Opened 2020-12-25 13:30 UTC by Code-Aditya-14

2020-12-25 14:17 UTC, Code-Aditya-14 commented
![image](https://user-images.githubusercontent.com/76389639/103136855-fe239080-46e9-11eb-82f9-0ba3de9ac213.png)

2020-12-25 16:10 UTC, debarghya472 requested changes
See the review and do the changes accordingly

2020-12-25 16:10 UTC, debarghya472 commented on connect.php
>  $user = 'root';
1. Delete the overheads! "<<<< HEAD ..."
2. Watch the videos to setup db 
3. Share screenshots of the working website on localhost

2020-12-26 06:45 UTC, debarghya472 reviewed
Also when ur **requested for changes**  after u commit u need to inform to **re-review**. Otherwise we won't be notified.

2020-12-26 06:45 UTC, debarghya472 commented on connect.php
> -$pass = DBPASSWORD;
@Code-Aditya-14 Do not hardcore $pass as sql password will be different for everyone. So instead create a config.php file with DBPASSWORD as key to store sql password. 

Follow the docs in [contributing.md](https://github.com/Infinito-IIT-Patna/Infinito2020/blob/master/CONTRIBUTING.md)

2020-12-26 17:59 UTC, Code-Aditya-14 commented
![image](https://user-images.githubusercontent.com/76389639/103156759-2edef500-47d2-11eb-91de-40cb16d7d7ed.png)

2020-12-26 18:21 UTC, debarghya472 requested changes
Good work! Just a new changes left and then ur good to go! If u have any doubts dm me

2020-12-26 18:21 UTC, debarghya472 commented on connect.php
>  <?php
Take account of the following points
1. do not remove include statement.
2. DBPASSWORD shouldn't be within single quotes ''

2020-12-27 07:52 UTC, debarghya472 approved these changes
good job!11

2020-12-27 07:52 UTC, merged